ssh $DHT_USER_NAME@csel-kh4250-19.cselabs.umn.edu "pkill -u $DHT_USER_NAME"
ssh $DHT_USER_NAME@csel-kh4250-20.cselabs.umn.edu "pkill -u $DHT_USER_NAME"
ssh $DHT_USER_NAME@csel-kh4250-21.cselabs.umn.edu "pkill -u $DHT_USER_NAME"
ssh $DHT_USER_NAME@csel-kh4250-22.cselabs.umn.edu "pkill -u $DHT_USER_NAME"
ssh $DHT_USER_NAME@csel-kh4250-23.cselabs.umn.edu "pkill -u $DHT_USER_NAME"
ssh $DHT_USER_NAME@csel-kh4250-24.cselabs.umn.edu "pkill -u $DHT_USER_NAME"
ssh $DHT_USER_NAME@csel-kh4250-26.cselabs.umn.edu "pkill -u $DHT_USER_NAME"