ssh $USER_NAME@csel-kh4250-19.cselabs.umn.edu "pkill -u $USER_NAME"
ssh $USER_NAME@csel-kh4250-20.cselabs.umn.edu "pkill -u $USER_NAME"
ssh $USER_NAME@csel-kh4250-21.cselabs.umn.edu "pkill -u $USER_NAME"
ssh $USER_NAME@csel-kh4250-22.cselabs.umn.edu "pkill -u $USER_NAME"
ssh $USER_NAME@csel-kh4250-23.cselabs.umn.edu "pkill -u $USER_NAME"
ssh $USER_NAME@csel-kh4250-24.cselabs.umn.edu "pkill -u $USER_NAME"
ssh $USER_NAME@csel-kh4250-25.cselabs.umn.edu "pkill -u $USER_NAME"
